---
#phantomjs

- name: Install libfontconfig
  action: apt pkg=libfontconfig state=latest install_recommends=yes
  tags: java

- name: Install unzip
  action: apt pkg=unzip state=latest install_recommends=yes
  tags: java

- name: Extract phantomjs archive
  unarchive: src=phantomjs-1.9.8-linux-x86_64.tar dest=/home/ubuntu
  tags: browsers

- name: Make dir /usr/lib/phantomjs/bin
  command: mkdir -p /usr/lib/phantomjs/bin
  tags: browsers

- name: Copy phantomjs binary to /usr/lib/phantomjs/bin
  command: cp /home/ubuntu/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/lib/phantomjs/bin creates=/usr/lib/phantomjs/bin/phantomjs
  tags: browsers