---

- name: Setup spark-master startup conf
  template: src=sparkmaster.conf dest=/etc/init/ owner=root group=root mode=0644
  tags: spark-master

- name: Setup spark-master log4j config
  template: src=log4j.properties dest={{spark_home}}/conf/ owner=root group=root mode=0644
  tags: spark-master