---

- name: Setup spark-master startup conf
  template: src=sparkmaster.conf dest=/etc/init/ owner=root group=root mode=0644
  tags: spark-master

- name: Setup spark-worker startup conf
  template: src=sparkworker.conf dest=/etc/init/ owner=root group=root mode=0644
  tags: spark-worker