- name: Environment to setup spark-master
  hosts: spark-master
  user: ubuntu
  sudo: yes

  roles:
    - common
    - browsers #shouldn't even be here, but just for integration test
    - spark
    - spark-master