---

#- name: Download Spark
#  shell: http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0.tgz
#  tags: common

#wget http://apache.mirror.nexicom.net/spark/spark-1.0.2/spark-1.0.2-bin-hadoop2.tgz
#tar -xf spark-1.0.0-bin-hadoop1.tgz -C /opt/spark/

- name: install ipython
  pip: name=ipython[notebook]
  tags: ipython

- name: copy profile config file to ipython root directory
  template: src=profile_spooky.template dest=/home/ubuntu/ owner=ubuntu group=ubuntu
  tags: spark-worker